# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) {|repo_name| "https://github.com/#{repo_name}"}

# gem "rails"

gem 'activerecord'
gem 'aws-sdk-s3'
gem 'bcrypt'
gem 'mysql2'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'

gem 'rake', require: false
gem 'rubocop', require: false
